name: Book CI

on:
  push:
    branches: [main]
    paths:
      - dune-book/**
  pull_request:
    branches: [main]

jobs:
  build_book:
    runs-on: ubuntu-22.04

    steps:
      - name: Partial Clone
        shell: bash
        run: |
          REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git clone -q --filter=blob:none --no-checkout --depth=1  --sparse $REPO .
          git sparse-checkout set dune-book
          git checkout

      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          image: ghcr.io/cpp-review-dune/introductory-review/xeus-cling-hdnum-git:latest
          options: -v ${{github.workspace}}:/work
          shell: bash
          run: |
            sudo pacman -Syu python-poetry texlive-latexextra texlive-fontsrecommended python-click python-docutils python-jinja python-jsonschema python-linkify-it-py python-sphinx-copybutton python-sphinxcontrib-bibtex python-yaml --noconfirm >/dev/null 2>&1
            sudo chown -R gitpod:gitpod /work
            cd /work/dune-book
            poetry config virtualenvs.in-project true
            poetry config virtualenvs.options.system-site-packages true
            poetry install
            poetry run jb build .

      - name: "Tar files"
        run: |
          sudo chown runner:docker -R .
          mv dune-book/_build .
          tar --zstd -cf Book.tar.zst _build

      - uses: actions/upload-artifact@v3
        with:
          name: Book-artifact
          path: Book.tar.zst
          if-no-files-found: error
          retention-days: 90