name: Deploy pages

on:
  push:
    branches: [main]
    paths:
      - dune-book/**
  pull_request:
    branches: [main]

jobs:
  deploy_pages:
    runs-on: ubuntu-22.04

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: book.yml
          name: Book-artifact

      - name: "Untar files"
        run: |
          tar -I zstd -xvf Book.tar.zst
          mkdir public
          mv _build/html/* public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          force_orphan: true
          publish_branch: gh-pages